### ISSUE TITLE
Error when running on Catalina

### ISSUE THREAD

**Issue by ahmedre** [drgrib/alfred-bear#4] opened 2019-10-13 21:46 UTC
Thanks for this awesome Alfred plugin! Just a heads up, on Catalina, using the scripts fail (I am guessing this is due to the executables not being signed).

The workaround I found is to open Alfred and right click the extension, choosing to view it in Finder. Then, go to the three executables (create, search, link) under cmd and right click each one and choose to run, accepting the warning. Afterwards, it seems to work fine, but would be awesome if this may be signed by default.

Thanks!

**Comment by drgrib** [comment] 2019-10-13 22:13
Hi. I'd be happy to do that but I don't experience this error (presumably because I create the executables myself). Do you have any idea how to sign executables for Catalina? I'm afraid I don't. If it involves paying for an Apple developer license, I can't justify doing that for a free plug-in I'm providing the community and may have to just provide instructions for doing what you did in the README.md.

**Comment by ahmedre** [comment] 2019-10-14 15:59
I unfortunately don't have experience with this either - but I did notice [on the QLStephen issue tracker](https://github.com/whomwah/qlstephen/issues/81) that people said it doesn't actually require the $99 developer license to notarize it - they link to [this Apple docs page](https://developer.apple.com/documentation/security/notarizing_your_app_before_distribution) about it.

**Comment by drgrib** [comment] 2019-10-15 20:13
I read through your links and came to this:
https://github.com/anthonygelibert/QLColorCode/issues/51#issuecomment-541235470

Looks like it still requires a developer account. I get why they are doing this but this seriously sucks for people trying to provide free plug-ins. They need an easier way for users to accept using plug-ins they are knowingly downloading from a third party.

**Comment by user68329** [comment] 2019-10-15 22:02
I don't see this as a big issue. I also had to "allow" the "app" and all I had to do is open the System Settings -> Security & Privacy -> General -> Allow.

Much like some of the other unsigned apps, it shows up here.

**Comment by drgrib** [comment] 2019-10-15 22:15
That's a relief to hear. I was hoping it would be that easy. I feel especially challenged in testing this because I don't receive this error as the author of the executables so I would have to jump through some hoops to reproduce it.

**Comment by thebucknerlife** [comment] 2020-05-11 19:37
@drgrib might be worth adding this to the README, I did the same thing as @blah43534. But many people might not know they need to go allow the unsigned app

**Comment by drgrib** [comment] 2020-06-02 14:01
Added:
https://github.com/drgrib/alfred-bear/blob/master/README.md#authorization

**Comment by aaazzz** [comment] 2021-05-26 02:55
For me, the simplest solution was to rebuild the executables myself.

1. right click the "Bear by dfgrib" workflow and select "Open in Terminal"
2. `cd cmd/create`, and you will find `create` and `main.go`
3. `rm create` to remove the existing executable file
4. `go build -o create main.go`, and you will have a new executable file
5. repeat 2-4 for `csearch`, `link`, `search` and `setcursor`

**Comment by rogiervandenberg** [comment] 2021-06-14 07:28
The issue is that Apples Gatekeeper restricts the apps to be executed if you're not the developer/builder and you have installed this from an 'unidentiefied developer'.

The reason why it works on @drgrib 's machine is because he's the author. That's also why it works when you compile the code yourself (as @aaazzz did). 

I [made a PR](https://github.com/drgrib/alfred-bear/pull/42) to add some additional installation-instructions, to overcome this issue. Meanwhile, if that is not merged yet, the fix is:

- Go to 'Workflows' section in Alfred Preferences
- Right click on 'Bear' by drgrib and select 'Open in Terminal'
- Copy this code and execute it `xattr -rd com.apple.quarantine cmd`

This will remove the quarantine attribute from the executables and allows them to be executed. This fixes the 'Permission Denied' errors.

**Comment by drgrib** [comment] 2023-07-22 19:14
I think this is resolved. Let me know if not.

**Closed as completed by drgrib** 2023-07-22 19:14 UTC
