### ISSUE TITLE
Feature request — open a tag

### ISSUE THREAD

**Issue by skotzko** [drgrib/alfred-bear#18] opened 2020-03-25 23:24 UTC
First of all, I just switched over to this extension from the former one I used. Great work, really enjoying it so far.

Feature request: it would be awesome to be able to quickly open a tag and see all notes in that view. 

Example: I take a lot of meeting notes for client projects, and tag them accordingly. So I have a tag like "work/randomClientName". 

It would be great to type `bt` into Alfred, start typing `randomClientName` and hit enter, and have it open the following x-callback-url (built from the [Bear tag builder](https://bear.app/xurlbuilder/open_tag/)): `bear://x-callback-url/open-tag?name=work%2FrandomClientName`

This would immediately drop me into Bear as if I'd clicked the tag in the tag list and show me all my notes within that tag.

**Comment by drgrib** [comment] 2020-03-26 01:01
I'm confused why you would want to be thrown back into the Bear client user interface instead of just having the workflow autocomplete you to:

```
bcs #work/randomClientName
```

or 

```
bs #work/randomClientName
```

and browse the notes filtered by that tag within Alfred.

The whole point of the workflow is to be able to browse Bear content without having to open the Bear client.

**Comment by drgrib** [comment] 2020-04-03 13:06
@skotzko Do you have a response to my comment above? Is the current filter by tag interface inadequate for browsing notes by tag somehow or did you just not know about it before asking?

**Comment by drgrib** [comment] 2020-04-05 23:01
Closing as duplicate of current functionality.

**Closed as completed by drgrib** 2020-04-05 23:01 UTC
